const ActionTypes = {
    ADD_TARGET_NUMBER: 'ADD_TARGET_NUMBER',
    ADD_COMPANIES: 'ADD_COMPANIES',
    SELECT_COMPANY_PRODUCTS: 'SELECT_COMPANY_PRODUCTS',
    SET_AUTH: 'SET_AUTH'
}

export default ActionTypes